export type SearchArtist = {
  artists: Array<{
    idArtist: string
    strArtist: string
    strArtistStripped: string
    strArtistAlternate: string
    strLabel: string
    idLabel: string
    intFormedYear: number
    intBornYear: number
    intDiedYear: number
    strDisbanded: string
    strStyle: string
    strGenre: string
    strMood: string
    strWebsite: string
    strFacebook: string
    strTwitter: string
    strBiographyEN: string
    strBiographyDE: string
    strBiographyFR: string
    strBiographyCN: string
    strBiographyIT: string
    strBiographyJP: string
    strBiographyRU: string
    strBiographyES: string
    strBiographyPT: string
    strBiographySE: string
    strBiographyNL: string
    strBiographyHU: string
    strBiographyNO: string
    strBiographyIL: string
    strBiographyPL: string
    strGender: string
    intMembers: number
    strCountry: string
    strCountryCode: string
    strArtistThumb: string
    strArtistLogo: string
    strArtistCutout: string
    strArtistClearart: string
    strArtistWideThumb: string
    strArtistFanart: string
    strArtistFanart2: string
    strArtistFanart3: string
    strArtistFanart4: string
    strArtistBanner: string
    strMusicBrainzID: string
    strISNIcode: string
    strLastFMChart: string
    intCharted: number
    strLocked: string
  }>
}

export type SearchAlbums = {
  album: Array<{
    idAlbum: string
    idArtist: string
    idLabel?: string
    strAlbum: string
    strAlbumStripped: string
    strArtist: string
    strArtistStripped: string
    intYearReleased: number
    strStyle?: string
    strGenre?: string
    strLabel?: string
    strReleaseFormat: string
    intSales?: number
    strAlbumThumb: string
    strAlbumThumbHQ: string
    strAlbumThumbBack: string
    strAlbumCDart?: string
    strAlbumSpine: string
    strAlbum3DCase: string
    strAlbum3DFlat: string
    strAlbum3DFace: string
    strAlbum3DThumb: string
    strDescription: string
    strDescriptionDE: string
    strDescriptionFR: string
    strDescriptionCN: string
    strDescriptionIT: string
    strDescriptionJP: string
    strDescriptionRU: string
    strDescriptionES: string
    strDescriptionPT: string
    strDescriptionSE: string
    strDescriptionNL: string
    strDescriptionHU: string
    strDescriptionNO: string
    strDescriptionIL: string
    strDescriptionPL: string
    intLoved: number
    intScore?: number
    intScoreVotes?: number
    strReview?: string
    strMood?: string
    strTheme?: string
    strSpeed?: string
    strLocation: string
    strMusicBrainzID: string
    strMusicBrainzArtistID: string
    strAllMusicID: string
    strBBCReviewID: string
    strRateYourMusicID: string
    strDiscogsID?: string
    strWikidataID?: string
    strWikipediaID?: string
    strGeniusID: string
    strLyricWikiID: string
    strMusicMozID: string
    strItunesID: string
    strAmazonID: string
    strLocked: string
    strDescriptionEN?: string
  }>
}
